### ISSUE TITLE
mavenize

### ISSUE THREAD

**Issue by albfan** [AlternateComputingSolutions/jsvn#5]
To ease develop (adopt TDD, divide subprojects) would be great to use maven istead of ant [convention vs configuration](https://en.wikipedia.org/wiki/Convention_over_configuration)

**Comment by albfan** [comment]
from that branch you can build project with:

```
$ mvn clean install
```

to execute

```
$ java -jar target/jsvn-0.8.jar
```

One problem detected from ant config file is tar.gz doesn't contain the testsuite

https://github.com/AlternateComputingSolutions/jsvn/blob/master/build.xml#L28

Do this really exists? It would be the entrypoint to add code coverage and TDD workflow

About ant and idea subprojects. Those should be in another project with a dependency from a jsvn-core.

**Comment by golpira** [comment]
Migrating to either Maven or Gradle would be good.  I also agree that breaking out ant and idea sub-modules would be good.

Why not then split out the JSVN gui code too, so that jsvn-core is purely "back-end" -- the code that interacts with the repositories.  A new "jsvn-ui" module could contain the swing code.  "jsvn-ant" would only depend on "jsvn-core" (no need to depend on the swing ui code.)

Any compelling reason to choose one build tool over the other (Maven vs Gradle)?

Thoughts?

**Comment by albfan** [comment]
Cool. I see it the same way. I detected same submodules as you.

About maven or gradle, I'm just comfortable with maven (lots of years using it) I think we can work in parallel to provide gradle config and see which fits better and is easy to maintain.

**Comment by albfan** [comment]
As soon as I have repos breaked I will push it. Don't know if I can create repos and transfer to and organization but for my split them totally is better than create a only repo with a submodule structure.

Did you ever use git submodules. Is a powerful concept but sometimes just add overhead to projects.
